name: Dev Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ProcessorEmulator.csproj
      
    - name: Build
      run: dotnet build ProcessorEmulator.csproj --no-restore --configuration Debug
      
    - name: Test
      run: dotnet test ProcessorEmulator.csproj --no-build --configuration Debug --verbosity normal
