name: .NET Build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore Processor-Emulator.sln

    - name: Build
      run: dotnet build Processor-Emulator.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Processor-Emulator.sln --no-build --verbosity normal
      continue-on-error: true
